[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pgn-extract-wg"
version = "0.0.1"
description = "Wrapper to build and install the pgn-extract binary"
authors = [{ name = "William Galvin" }]
