name: Build and Publish PyPI

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build wheels and sdist on ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: linux-x86_64
            runs-on: ubuntu-latest
            arch: x86_64
          - os: linux-aarch64
            runs-on: ubuntu-latest
            arch: aarch64
          - os: macos-x86_64
            runs-on: macos-13
            arch: x86_64
          - os: macos-aarch64
            runs-on: macos-latest
            arch: arm64
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install uv
        run: pip install uv

      - name: Build
        run: uv build

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/*

  publish_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: 'dist-*'
          path: dist
          merge-multiple: true

      - name: Install Twine
        run: pip install twine

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload --non-interactive --skip-existing dist/*
